"""add user_id to kb_documents

Revision ID: 588db236ff35
Revises: 76174a24da7c
Create Date: 2026-06-20 11:41:54.011000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588db236ff35'
down_revision: Union[str, Sequence[str], None] = '76174a24da7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_documents', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.execute("UPDATE kb_documents SET user_id = '21baa74a-5fb0-4cad-bac6-77a355f0e6a2'")
    op.alter_column('kb_documents', 'user_id', nullable=False)
    op.create_foreign_key('kb_documents_user_id_fkey', 'kb_documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('kb_documents_user_id_fkey', 'kb_documents', type_='foreignkey')
    op.drop_column('kb_documents', 'user_id')
    # ### end Alembic commands ###
