from sqlalchemy import select
from sqlalchemy.orm import Session
from uuid import UUID
import logging
from dotenv import load_dotenv
import os
from src.legal_rag.models import KnowledgeBase, KbDocuments, Users
from sqlalchemy import MetaData, Table, insert, create_engine, text
from sqlalchemy.exc import IntegrityError

load_dotenv()  

DATABASE_URL = os.getenv("DATABASE_URL")
engine = create_engine(DATABASE_URL)

def get_or_create_kb_data(engine, user_id: str | UUID, filename: str) -> dict: 
    """
    Finds or creates a Knowledge Base for the user, and inserts a new document record.
    Wraps the entire process in a safe transaction.
    """

    # Define a constant identifier for your single global KB
    GLOBAL_KB_NAME = "Global_Unified_KB"

    # 1. Create the session 'db' using the engine you passed in
    with Session(engine) as db:
        try:
            # --- STEP 1 & 2: Find or Create Knowledge Base ---
            query = select(KnowledgeBase).where(KnowledgeBase.name == GLOBAL_KB_NAME)
            result = db.execute(query)
            kb = result.scalars().first()

            if not kb:
                # First time upload: Create new Knowledge Base
                kb = KnowledgeBase(
                    user_id=user_id,
                    name=GLOBAL_KB_NAME, 
                    description="Unified Knowledge Base for all the user's documents.",
                    is_active=True
                )
                db.add(kb)
                db.flush() # Generates kb.id without committing the transaction yet

            # --- STEP 3: Create the Document Record ---
            # Used KbDocuments to match your models.py, and filename from arguments
            new_document = KbDocuments(
                knowledge_base_id=kb.id,
                user_id=user_id,
                title=filename, 
                document_type="pdf",
                status="pending_processing" 
            )
            db.add(new_document)
            
            # Commit the transaction so both records are permanently saved
            db.commit()
            db.refresh(new_document)

            return {
                "status": "success",
                "message": "File metadata saved successfully. Processing started.",
                "knowledge_base_id": str(kb.id),
                "document_id": str(new_document.id)
            }

        except Exception as e:
            # If ANYTHING fails above, undo the entire transaction
            db.rollback()
            logging.error(f"Database transaction failed: {str(e)}")
            return {
                "status": "error",
                "message": f"Failed to save to database. Details: {str(e)}"
            }
        
def update_document_status(engine, document_id: str | UUID) -> dict:
    """
    Updates the status of a document in the KbDocuments table.
    """
    with Session(engine) as db:
        try:
            # Modern SQLAlchemy 2.0 syntax
            query = select(KbDocuments).where(KbDocuments.id == document_id)
            result = db.execute(query)
            
            # .scalars().first() grabs the actual User object
            document = result.scalars().first() 
            
            if document:
                document.status = "completed"
                db.commit()
                return {
                    "status": "success",
                    "message": f"Document {document_id} status updated to completed."
                }
            
        except Exception as e:
            logging.error(f"Database error during updating stauss for {document_id}: {str(e)}")
            return None
        
def get_user_kb_docs(engine, user_id: str | UUID) -> list[dict]:
    with Session(engine) as db:
        try:
            query = select(KbDocuments).where(KbDocuments.user_id == select(Users.id).where(Users.id == user_id))
            result = db.execute(query)

            row = result.scalars().all()
            return row

        except Exception as e:
            logging.error(f"Database error during retrieval of user documents for {user_id}: {str(e)}")
            return None


def load_user_data(engine, name: str, email: str, password_hash: str, role: str) -> dict:
    """
    Inserts a new user into the database using the SQLAlchemy ORM.
    Expects the password to ALREADY be hashed before being passed in.
    """
    with Session(engine) as db:
        try:
            # 1. Create the Python object representing the new row
            new_user = Users(
                name=name,
                email=email,
                password_hash=password_hash,
                role=role
            )
            
            # 2. Add and commit to the database
            db.add(new_user)
            db.commit()
            db.refresh(new_user) # Retrieves the new ID generated by PostgreSQL
            
            return {
                "status": "success",
                "message": f"User '{email}' was successfully loaded.",
                "user_id": str(new_user.id)
            }
            
        except IntegrityError:
            # The db.rollback() is critical here! If you don't roll back after an 
            # IntegrityError, the session gets permanently "stuck" for future queries.
            db.rollback() 
            return {
                "status": "error",
                "message": f"A user with the email '{email}' already exists."
            }
            
        except Exception as e:
            db.rollback()
            logging.error(f"Failed to create user {email}: {str(e)}")
            return {
                "status": "error",
                "message": "An unexpected error occurred while creating the user."
            }
    
def get_user_by_email(engine, email: str) -> dict | None:
    with Session(engine) as db:
        try:
            # Modern SQLAlchemy 2.0 syntax
            query = select(Users).where(Users.email == email)
            result = db.execute(query)
            
            # .scalars().first() grabs the actual User object
            user = result.scalars().first()
            
            return user
            
        except Exception as e:
            logging.error(f"Database error during retrieval for {email}: {str(e)}")
            return None
        
# def load_user_data(engine,name: str, email: str, password_hash: str, role: str) -> str:
#     """
#     Reflects the existing table and inserts the provided user data.
#     """
#     # 1. Write the raw INSERT query using parameterized placeholders (:variable)
#     query = text("""
#         INSERT INTO users (name, email, password_hash, role) 
#         VALUES (:name, :email, :password_hash, :role)
#     """)
    
#     try:
#         with engine.begin() as connection:
#             connection.execute(query, {
#                 "name": name,
#                 "email": email,
#                 "password_hash": password_hash,
#                 "role": role
#             })
            
#         return f"Success: User '{email}' was successfully loaded into the database."
        
#     except IntegrityError:
#         # Fails gracefully if the email violates a UNIQUE constraint in your DB
#         return f"Failure: A user with the email '{email}' already exists."
        
#     except Exception as e:
#         return f"Failure: An error occurred while loading the data. Details: {str(e)}"


# def get_user_by_email(engine, email: str) -> dict | None:
#     """
#     Retrieves user data by email using a raw SQL query.
#     """
#     # IMPORTANT: Use :email as a placeholder for parameterized queries!
#     query = text("SELECT * FROM users WHERE email = :email")
    
#     try:
#         with engine.connect() as connection:
#             # Execute the query, binding the dictionary payload to the placeholders
#             result = connection.execute(query, {"email": email}).fetchone()
            
#             if result:
#                 # Convert the result into a standard Python dictionary
#                 return dict(result._mapping)
#             else:
#                 return None
                
#     except Exception as e:
#         print(f"Database error during retrieval: {str(e)}")
#         return None